-- ==============================================================================
-- Mounir Smart LMS — Complete Supabase PostgreSQL Schema & Seed Data (v1.0)
-- ==============================================================================

DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS quiz_submissions CASCADE;
DROP TABLE IF EXISTS quiz_questions CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS support_tickets CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS teacher_payouts CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS lectures CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP TABLE IF EXISTS courses CASCADE;

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    track_name TEXT NOT NULL,
    target_age TEXT NOT NULL,
    description TEXT,
    icon TEXT DEFAULT '',
    price_per_block NUMERIC(10, 2) DEFAULT 450.00,
    total_lectures INT DEFAULT 8,
    default_day TEXT DEFAULT 'السبت',
    default_time TEXT DEFAULT '18:00',
    min_age INT DEFAULT 10,
    max_age INT DEFAULT 18,
    max_capacity INT DEFAULT 6,
    default_duration_minutes INT DEFAULT 60,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    bio TEXT,
    active INT DEFAULT 1,
    rate_per_session NUMERIC(10, 2) DEFAULT 150.00,
    rate_per_private_session NUMERIC(10, 2) DEFAULT 80.00,
    late_count INT DEFAULT 0,
    cancellation_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    student_code TEXT NOT NULL UNIQUE,
    age INT DEFAULT 12,
    phone TEXT,
    parent_name TEXT,
    parent_phone TEXT,
    qr_code TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'teacher', 'student')),
    related_id BIGINT,
    student_id BIGINT REFERENCES students(id) ON DELETE SET NULL,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    course_name TEXT NOT NULL,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
    unlocked_blocks INT DEFAULT 1,
    total_lectures_unlocked INT DEFAULT 4,
    renewal_count INT DEFAULT 0,
    remaining_credits INT DEFAULT 4,
    excuse_count INT DEFAULT 0,
    max_allowed_excuses INT DEFAULT 1,
    current_surah TEXT DEFAULT 'سورة الفاتحة والبقرة',
    current_aya INT DEFAULT 1,
    status TEXT DEFAULT 'active',
    enrolled_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE lectures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name TEXT NOT NULL,
    lecture_number INT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    block_number INT DEFAULT 1,
    scheduled_time TEXT NOT NULL,
    google_meet_url TEXT DEFAULT '',
    drive_recording_url TEXT DEFAULT '',
    drive_materials_url TEXT DEFAULT '',
    calendar_title TEXT DEFAULT '',
    status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'live', 'completed', 'postponed')),
    postpone_reason TEXT,
    rescheduled_to TEXT,
    duration_minutes INT DEFAULT 60,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    lecture_id BIGINT REFERENCES lectures(id) ON DELETE CASCADE,
    course_name TEXT NOT NULL,
    status TEXT DEFAULT 'present' CHECK (status IN ('present', 'attended', 'excused', 'absent', 'late')),
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    duration_minutes INT DEFAULT 60
);

CREATE TABLE quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name TEXT NOT NULL,
    block_number INT DEFAULT 1,
    title TEXT NOT NULL,
    description TEXT,
    total_score INT DEFAULT 50,
    time_limit_minutes INT DEFAULT 20,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option TEXT NOT NULL,
    points INT DEFAULT 10
);

CREATE TABLE quiz_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    score INT NOT NULL,
    max_score INT DEFAULT 50,
    percentage NUMERIC(5, 2),
    status TEXT DEFAULT 'passed',
    answers_json JSONB,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE SET NULL,
    student_name TEXT,
    course_name TEXT DEFAULT 'عام',
    category TEXT DEFAULT 'عام',
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
    admin_reply TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    course_name TEXT,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'general',
    action_url TEXT,
    is_read INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE SET NULL,
    course_name TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    currency TEXT DEFAULT 'EGP',
    block_unlocked INT DEFAULT 2,
    transaction_id TEXT UNIQUE,
    receipt_number TEXT UNIQUE,
    payment_method TEXT DEFAULT 'card',
    status TEXT DEFAULT 'completed',
    whatsapp_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE teacher_payouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
    amount NUMERIC(10, 2) NOT NULL,
    sessions_count INT DEFAULT 8,
    period_month TEXT NOT NULL,
    status TEXT DEFAULT 'paid',
    payment_method TEXT DEFAULT 'instapay',
    reference_number TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE lectures ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_payouts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "courses_all" ON courses FOR ALL USING (true);
CREATE POLICY "teachers_all" ON teachers FOR ALL USING (true);
CREATE POLICY "students_all" ON students FOR ALL USING (true);
CREATE POLICY "users_all" ON users FOR ALL USING (true);
CREATE POLICY "enrollments_all" ON enrollments FOR ALL USING (true);
CREATE POLICY "lectures_all" ON lectures FOR ALL USING (true);
CREATE POLICY "attendance_all" ON attendance FOR ALL USING (true);
CREATE POLICY "quizzes_all" ON quizzes FOR ALL USING (true);
CREATE POLICY "quiz_questions_all" ON quiz_questions FOR ALL USING (true);
CREATE POLICY "quiz_submissions_all" ON quiz_submissions FOR ALL USING (true);
CREATE POLICY "support_tickets_all" ON support_tickets FOR ALL USING (true);
CREATE POLICY "notifications_all" ON notifications FOR ALL USING (true);
CREATE POLICY "payments_all" ON payments FOR ALL USING (true);
CREATE POLICY "teacher_payouts_all" ON teacher_payouts FOR ALL USING (true);

INSERT INTO courses (id, name, track_name, target_age, description, price_per_block, total_lectures, default_day, default_time, min_age, max_age, max_capacity, default_duration_minutes)
VALUES
(1, 'كتالوج الشباب 2.0', 'مسار البنين', '12 - 16 سنة', 'بناء الشخصية القيادية والذكاء المالي والتعامل مع الضغوط.', 450.00, 8, 'السبت', '18:00', 12, 16, 6, 60),
(2, 'وعي وأمان (للبنات)', 'مسار الفتيات', '11 - 15 سنة', 'الأمان النفسي والرقمي، العلاقات الصحية، والأنوثة الواعية.', 450.00, 8, 'الجمعة', '17:00', 11, 15, 6, 60),
(3, 'قصص الأنبياء (سر الحاج إسماعيل)', 'مسار الناشئة', '8 - 12 سنة', 'استخلاص القيم والدروس الحياتية من سير الأنبياء بطريقة درامية.', 400.00, 8, 'السبت', '16:00', 8, 12, 5, 45),
(4, 'مسار القرآن الكريم والتدبر', 'مسار القرآن الفردي', '6 - 18 سنة', 'حفظ متقن وتدبر عملي يومي لسور الفاتحة والكهف وجزء عم.', 350.00, 8, 'الأحد', '18:30', 6, 18, 1, 45);

INSERT INTO teachers (id, name, specialty, email, phone, bio, rate_per_session, rate_per_private_session, active)
VALUES
(1, 'الشيخ أحمد منصور', 'مسار القرآن الكريم والقراءات والتجويد', 'ahmed.mansour@monir-academy.com', '01001112233', 'إجازة في القراءات العشر وخبرة 12 سنة في تدريب وتدبر القرآن للأطفال والشباب.', 150.00, 80.00, 1),
(2, 'أ. محمود سامي', 'مسار كتالوج الشباب وبناء الشخصية القيادية', 'mahmoud.sami@monir-academy.com', '01004445566', 'استشاري تربوي وتطوير مهارات القيادة والذكاء المالي للمراهقين.', 180.00, 90.00, 1),
(3, 'أ. سارة عبدالحميد', 'مسار وعي وأمان للبنات والصحة النفسية', 'sara.abdelhamid@monir-academy.com', '01007778899', 'أخصائية نفسية وتربوية معتمدة ومتخصصة في توجيه الفتيات.', 160.00, 80.00, 1),
(4, 'أ. يوسف إبراهيم', 'مسار السيرة النبوية وقصص الأنبياء', 'youssef.ibrahim@monir-academy.com', '01009990011', 'باحث في التاريخ الإسلامي وأسلوب الحكي الدرامي للناشئة.', 140.00, 70.00, 1);

INSERT INTO students (id, name, student_code, age, phone, parent_name, parent_phone, qr_code)
VALUES
(1, 'عمر أحمد علي', 'MNR-2026-1042', 14, '01025802503', 'أحمد علي حسن', '01002530197', 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=MNR-2026-1042'),
(2, 'مريم حسام الدين', 'MNR-2026-2055', 13, '01145892301', 'حسام الدين فؤاد', '01123456789', 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=MNR-2026-2055'),
(3, 'يوسف محمود سالم', 'MNR-2026-3012', 9, '01234567890', 'محمود سالم', '01298765432', 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=MNR-2026-3012'),
(4, 'عبدالرحمن خالد', 'MNR-2026-4088', 11, '01099887766', 'خالد عبدالرحيم', '01011223344', 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=MNR-2026-4088');

INSERT INTO users (id, username, password_hash, role, related_id, student_id, teacher_id, full_name, email, phone)
VALUES
(1, 'admin', 'admin2026', 'admin', 1, NULL, NULL, 'إدارة أكاديمية منير', 'admin@monir-academy.edu.eg', '01000000000'),
(2, 'eman.naggar', '123456', 'teacher', 1, NULL, 1, 'أ. إيمان النجار', 'eman.naggar@monir-academy.edu.eg', '01001112233'),
(3, 'sara.abdelmonem', '123456', 'teacher', 2, NULL, 2, 'د. سارة عبد المنعم', 'sara.abdelmonem@monir-academy.edu.eg', '01002223344'),
(4, 'omar.hossam', '123456', 'teacher', 3, NULL, 3, 'م. عمر حسام', 'omar.hossam@monir-academy.edu.eg', '01003334455'),
(5, 'youssef.hani', '123456', 'teacher', 4, NULL, 4, 'م. يوسف هاني', 'youssef.hani@monir-academy.edu.eg', '01004445566'),
(6, 'abdelrahman', '123456', 'student', 4, 4, NULL, 'عبدالرحمن خالد محمود', 'abdelrahman@student.monir.edu.eg', '01012345678'),
(7, 'mariam', '123456', 'student', 2, 2, NULL, 'مريم حسام الدين', 'mariam@student.monir.edu.eg', '01145892301');

INSERT INTO enrollments (student_id, course_name, teacher_id, unlocked_blocks, total_lectures_unlocked, remaining_credits, excuse_count, current_surah)
VALUES
(1, 'كتالوج الشباب 2.0', 2, 2, 8, 4, 0, 'المرحلة الثانية - القيادة'),
(1, 'مسار القرآن الكريم والتدبر', 1, 1, 4, 2, 0, 'سورة الرحمن - المرحلة الأولى'),
(2, 'وعي وأمان (للبنات)', 3, 1, 4, 4, 0, 'المرحلة الأولى - الوعي الذاتي'),
(4, 'مسار القرآن الكريم والتدبر', 1, 2, 8, 1, 1, 'سورة ق - المرحلة الثانية');

SELECT setval('courses_id_seq', (SELECT MAX(id) FROM courses));
SELECT setval('teachers_id_seq', (SELECT MAX(id) FROM teachers));
SELECT setval('students_id_seq', (SELECT MAX(id) FROM students));
SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));
SELECT setval('enrollments_id_seq', (SELECT MAX(id) FROM enrollments));
